name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # The checkout step copies your repo into the action runner. Important!
      - uses: actions/checkout@v4
      # When the dist_dir is ready, deploy it to neocities
      # Here we deploy the folder named `public`
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: true # set this to true if you have a supporter account and want to bypass unsuported files filter.
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload.
          dist_dir: public
          protected_files: |
            archives/scripts/webdeck\\-player/script.js
            archives/scripts/webdeck\\-player/themes/default/about.txt
            archives/scripts/webdeck\\-player/themes/default/fonts/licenses/slkscr.txt
            archives/scripts/webdeck\\-player/themes/default/fonts/slkscr.ttf
            archives/scripts/webdeck\\-player/themes/default/images/green-light-off.gif
            archives/scripts/webdeck\\-player/themes/default/images/green-light-on.gif
            archives/scripts/webdeck\\-player/themes/default/images/info.png
            archives/scripts/webdeck\\-player/themes/default/images/mute.png
            archives/scripts/webdeck\\-player/themes/default/images/next.png
            archives/scripts/webdeck\\-player/themes/default/images/pause.png
            archives/scripts/webdeck\\-player/themes/default/images/play.png
            archives/scripts/webdeck\\-player/themes/default/images/prev.png
            archives/scripts/webdeck\\-player/themes/default/images/slider.gif
            archives/scripts/webdeck\\-player/themes/default/images/sound.png
            archives/scripts/webdeck\\-player/themes/default/images/stop.png
            archives/scripts/webdeck\\-player/themes/default/logo.png
            archives/scripts/webdeck\\-player/themes/default/webdeck-player.css
            archives/scripts/webdeck\\-player/themes/minimal/about.txt
            archives/scripts/webdeck\\-player/themes/minimal/fonts/licenses/slkscr.txt
            archives/scripts/webdeck\\-player/themes/minimal/fonts/slkscr.ttf
            archives/scripts/webdeck\\-player/themes/minimal/images/green-light-off.gif
            archives/scripts/webdeck\\-player/themes/minimal/images/green-light-on.gif
            archives/scripts/webdeck\\-player/themes/minimal/images/info.png
            archives/scripts/webdeck\\-player/themes/minimal/images/mute.png
            archives/scripts/webdeck\\-player/themes/minimal/images/next.png
            archives/scripts/webdeck\\-player/themes/minimal/images/pause.png
            archives/scripts/webdeck\\-player/themes/minimal/images/play.png
            archives/scripts/webdeck\\-player/themes/minimal/images/prev.png
            archives/scripts/webdeck\\-player/themes/minimal/images/slider.gif
            archives/scripts/webdeck\\-player/themes/minimal/images/sound.png
            archives/scripts/webdeck\\-player/themes/minimal/images/stop.png
            archives/scripts/webdeck\\-player/themes/minimal/logo.png
            archives/scripts/webdeck\\-player/themes/minimal/webdeck-player.css
            archives/scripts/webdeck\\-player/themes/red-grunge/about.txt
            archives/scripts/webdeck\\-player/themes/red-grunge/fonts/licenses/slkscr.txt
            archives/scripts/webdeck\\-player/themes/red-grunge/fonts/slkscr.ttf
            archives/scripts/webdeck\\-player/themes/red-grunge/images/background.jpg
            archives/scripts/webdeck\\-player/themes/red-grunge/images/green-light-off.gif
            archives/scripts/webdeck\\-player/themes/red-grunge/images/green-light-on.gif
            archives/scripts/webdeck\\-player/themes/red-grunge/images/info.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/mute.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/next.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/pause.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/play.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/prev.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/slider.gif
            archives/scripts/webdeck\\-player/themes/red-grunge/images/sound.png
            archives/scripts/webdeck\\-player/themes/red-grunge/images/stop.png
            archives/scripts/webdeck\\-player/themes/red-grunge/logo.png
            archives/scripts/webdeck\\-player/themes/red-grunge/webdeck-player.css
            archives/scripts/webdeck\\-player/themes/silver/about.txt
            archives/scripts/webdeck\\-player/themes/silver/fonts/EurostileExtendedBlack.ttf
            archives/scripts/webdeck\\-player/themes/silver/fonts/LED-Dot-Matrix.ttf
            archives/scripts/webdeck\\-player/themes/silver/fonts/licenses/slkscr.txt
            archives/scripts/webdeck\\-player/themes/silver/fonts/slkscr.ttf
            archives/scripts/webdeck\\-player/themes/silver/images/green-light-off.gif
            archives/scripts/webdeck\\-player/themes/silver/images/green-light-on.gif
            archives/scripts/webdeck\\-player/themes/silver/images/info.png
            archives/scripts/webdeck\\-player/themes/silver/images/mute.png
            archives/scripts/webdeck\\-player/themes/silver/images/next.png
            archives/scripts/webdeck\\-player/themes/silver/images/pause.png
            archives/scripts/webdeck\\-player/themes/silver/images/play.png
            archives/scripts/webdeck\\-player/themes/silver/images/prev.png
            archives/scripts/webdeck\\-player/themes/silver/images/sound.png
            archives/scripts/webdeck\\-player/themes/silver/images/stop.png
            archives/scripts/webdeck\\-player/themes/silver/logo.png
            archives/scripts/webdeck\\-player/themes/silver/webdeck-player.css
            archives/scripts/webdeck\\-player/themes/violet/about.txt
            archives/scripts/webdeck\\-player/themes/violet/fonts/DS-DIGII.TTF
            archives/scripts/webdeck\\-player/themes/violet/fonts/EurostileExtendedBlack.ttf
            archives/scripts/webdeck\\-player/themes/violet/fonts/licenses/DIGITAL.TXT
            archives/scripts/webdeck\\-player/themes/violet/fonts/licenses/slkscr.txt
            archives/scripts/webdeck\\-player/themes/violet/images/green-light-off.gif
            archives/scripts/webdeck\\-player/themes/violet/images/green-light-on.gif
            archives/scripts/webdeck\\-player/themes/violet/images/info.png
            archives/scripts/webdeck\\-player/themes/violet/images/mute.png
            archives/scripts/webdeck\\-player/themes/violet/images/next.png
            archives/scripts/webdeck\\-player/themes/violet/images/pause.png
            archives/scripts/webdeck\\-player/themes/violet/images/play.png
            archives/scripts/webdeck\\-player/themes/violet/images/prev.png
            archives/scripts/webdeck\\-player/themes/violet/images/sound.png
            archives/scripts/webdeck\\-player/themes/violet/images/stop.png
            archives/scripts/webdeck\\-player/themes/violet/logo.png
            archives/scripts/webdeck\\-player/themes/violet/webdeck-player.css
            archives/scripts/webdeck\\-player/webdeck.html
